/*
 * This source file was generated by the Gradle 'init' task
 */
package nepbot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class NepBotTest { 

    public NepBotTest() {
    }
    
}
